New final-status

diff --git a/.github/workflows/check-packages.yml b/.github/workflows/check-packages.yml
--- a/.github/workflows/check-packages.yml
+++ b/.github/workflows/check-packages.yml
@@ -51,3 +51,21 @@ jobs:
         run: brew install ${{ env.PACKAGE_NAME }}
       - name: Uninstall package
         run: brew uninstall ${{ env.PACKAGE_NAME }}
+
+  # Status check that is required in branch protection rules.
+  final-status:
+    name: Final status
+    needs:
+      - changed-packages
+      - verify-packages
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: Check
+        run: |
+          results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}')
+          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
+            echo "One or more required jobs failed"
+            exit 1
+          fi
+          echo "All required jobs completed successfully."
