Check PACKAGE_NAME is mentioned in the README.md

diff --git a/.github/workflows/check-packages.yml b/.github/workflows/check-packages.yml
--- a/.github/workflows/check-packages.yml
+++ b/.github/workflows/check-packages.yml
@@ -42,6 +42,13 @@ jobs:
       - name: Check Package
         run: |
           PACKAGE_NAME="$(basename "${{ matrix.packages }}" .rb)"
+
+          README_FILE=$(ls README.md 2>/dev/null | head -n1 || true)
+          if ! grep -qi -w -- "`$PACKAGE_NAME`" "$README_FILE"; then
+            echo "Package \`$PACKAGE_NAME\` not found in \`$README_FILE\`"
+            exit 1
+          fi
+
           printf "\033[32m==>\033[0m \033[1;30mLinting\033[0m \033[1;32m%s\033[0m\n" "$PACKAGE_NAME"
           brew style "$PACKAGE_NAME"
           printf "\033[32m==>\033[0m \033[1;30mAuditing\033[0m \033[1;32m%s\033[0m\n" "$PACKAGE_NAME"
